services:
  backend:
    environment:
      NODE_ENV: production
    ports: []  # hidden in prod, only proxy exposes HTTP

  frontend:
    ports: []  # served via proxy

  db:
    ports: []  # never expose Postgres publicly

  proxy:
    # Build a custom lightweight nginx image that already contains our config,
    # removing the need for a bind mount (fixes rootless bind issues under /opt).
    container_name: notatnik-proxy
    build:
      context: ./nginx
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/health || exit 1"]        
      interval: 15s
      timeout: 5s
      retries: 5

# To enable HTTPS later add certbot sidecar or switch to Caddy.
